'''


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


'''

max_value = 4e6
old_fib,new_fib = (1,2)
result = 0


def fib(a,b):
    return a+b

while new_fib < max_value:
    if (new_fib % 2 == 0):
        result += new_fib

    new = fib(new_fib,old_fib)
    new_fib,old_fib = new,new_fib

print(result)